# Generated by Django 4.0.2 on 2022-05-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='khoa',
            name='pre_khoa',
            field=models.ManyToManyField(null=True, to='rooms.Khoa'),
        ),
    ]
