# Generated by Django 4.0.2 on 2022-05-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_khoa_pre_khoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'like'), (1, 'haha'), (2, 'heart')], default=0),
        ),
    ]
