# Generated by Django 4.0.2 on 2022-05-15 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_roomview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomview',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
        ),
    ]
